import "./globals.css";
<<<<<<< HEAD

export const metadata = {
  title: "ZAINKEEPSCODE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
=======
import {Josefin_Sans}from 'next/font/google';
export const metadata = {
  title: "Rii_Digital",
  description: "Generated by create next app",
};
const Josef=Josefin_Sans({
  subsets:['latin'],
  weigth:["100","200","300","400","500","600","700"],
  display:"swap",

})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body classname={Josef.className}>{children}</body>
>>>>>>> origin/main
    </html>
  );
}
